name: Docker image build CI - build docker image.

on:
  release:
    types: [ published ]

jobs:
  docker:
    name: docker build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # https://github.com/actions/checkout
      - name: Checkout codebase
        uses: actions/checkout@v2

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        # Only login if not a PR, as PRs only trigger a Docker build and not a push
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          # Use tags / labels provided by 'docker/metadata-action' above
          tags: ${{ github.event.release.tag_name }}
          labels: Release ${{ github.event.release.tag_name }}
